### ISSUE TITLE
import error in CRAN checks

### ISSUE THREAD

**Issue by brandmaier** [brandmaier/semtree#50]
semtree checks currently produce the following problem:
```
N  checking dependencies in R code (4s)
   '::' oder ':::' importieren unangemeldet aus:
     'ctsemOMX' 'expm'
   Unexported object imported by a ':::' call: 'OpenMx:::vcov.MxModel'
```

Please fix, @manuelarnold

**Comment by brandmaier** [comment]
Further problems related to the latest contributions are:

```
   checkBinSize: no visible binding for global variable 'meta'
   ctsemScores: no visible global function definition for 'na.omit'
   plotParContrib: no visible binding for global variable 'Node'
   plotParContrib: no visible binding for global variable 'Parameter'
   plotParContrib: no visible binding for global variable 'Contribution'
   Undefined global functions or variables:
     Contribution Node Parameter meta na.omit
   Consider adding
     importFrom("stats", "na.omit")
```

Please try to run CRAN checks before creating pull requests if possible. Thanks!

**Comment by manuelarnold** [comment]
Sorry. I always forget that :D It is all fixed now.

**Comment by manuelarnold** [comment]
The following notes will be back in the new version:

   plotParContrib: no visible binding for global variable 'Node'
   plotParContrib: no visible binding for global variable 'Parameter'
   plotParContrib: no visible binding for global variable 'Contribution'

These notes happen because of the way ggplot2 works. I googled a little about these notes, and the ggplot2 developers seem to suggest to just ignore these notes. They are not errors or warnings.

**Comment by brandmaier** [comment]
Fixed here https://github.com/brandmaier/semtree/commit/77e70e3d25913fa3496febc973613cf293bf271c
